# Generated by Django 6.0.3 on 2026-03-27 08:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'phone_category',
            },
        ),
        migrations.CreateModel(
            name='Phones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model', models.CharField(max_length=50)),
                ('brand', models.CharField(choices=[('SAMSUNG', 'Samsung'), ('REALME', 'Realme'), ('APPLE', 'Apple'), ('XIAOMI', 'Xiaomi'), ('OPPO', 'Oppo')], default='SAMSUNG', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('photo', models.ImageField(upload_to='phones/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'JPG', 'PNG'])])),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2026)])),
                ('desc', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phone.category')),
            ],
            options={
                'db_table': 'phones',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='PhoneOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.CharField(max_length=50)),
                ('count', models.PositiveIntegerField()),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phone.phones')),
            ],
            options={
                'db_table': 'phone_order',
                'ordering': ['-id'],
            },
        ),
    ]
