# Generated by Django 6.0.3 on 2026-03-27 08:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model', models.CharField(max_length=50)),
                ('brand', models.CharField(choices=[('SAMSUNG', 'Samsung'), ('REALME', 'Realme'), ('APPLE', 'Apple'), ('XIAOMI', 'Xiaomi'), ('OPPO', 'Oppo')], default='SAMSUNG', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('photo', models.ImageField(upload_to='phone/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'JPG', 'PNG', 'webp'])])),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2026)])),
                ('desc', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phone.category')),
            ],
            options={
                'db_table': 'phone',
                'ordering': ['-id'],
            },
        ),
        migrations.AlterField(
            model_name='phoneorder',
            name='phone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phone.phone'),
        ),
        migrations.DeleteModel(
            name='Phones',
        ),
    ]
